- name: Install HAProxy on Ubuntu Servers
  hosts: linuxservers
  become: yes
  tasks:
    - name: Install Socat
      apt:
        name: socat
        state: present
        update_cache: yes

    - name: Install HAProxy
      apt:
        name: haproxy
        state: present
        update_cache: yes

    - name: Configure HAProxy
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
      notify:
        - Restart HAProxy

    - name: Ensure HAProxy is running and enabled
      service:
        name: haproxy
        state: started
        enabled: yes

  handlers:
    - name: Restart HAProxy
      service:
        name: haproxy
        state: restarted