---
- name: Install Grafana on Ubuntu
  hosts: linuxserver
  become: yes
  vars:
    grafana_ini_path: /etc/grafana/grafana.ini
    grafana_server_name: "grafana.example.com"
    grafana_root_url: "https://grafana.example.com"

  tasks:
    - name: Install required dependencies
      apt:
        name:
          - apt-transport-https
          - software-properties-common
          - wget
        state: present
        update_cache: yes

    - name: Add Grafana APT key
      apt_key:
        url: https://apt.grafana.com/gpg.key
        state: present

    - name: Add Grafana APT repository
      apt_repository:
        repo: "deb https://apt.grafana.com stable main"
        state: present
        filename: grafana

    - name: Install Grafana
      apt:
        name: grafana
        state: present
        update_cache: yes

    - name: Ensure grafana.ini has correct server name
      ini_file:
        path: "{{ grafana_ini_path }}"
        section: "server"
        option: "domain"
        value: "{{ grafana_server_name }}"
        backup: yes

    - name: Ensure grafana.ini has correct root_url
      ini_file:
        path: "{{ grafana_ini_path }}"
        section: "server"
        option: "root_url"
        value: "{{ grafana_root_url }}"
        backup: yes
        
    - name: Enable and start Grafana service
      systemd:
        name: grafana-server
        enabled: yes
        state: started

    # Optional: Open firewall port 3000 (uncomment if using UFW)
    # - name: Allow Grafana port through UFW
    #   ufw:
    #     rule: allow
    #     port: 3000
    #     proto: tcp