---
- name: Install and configure HAProxy for HTTPS passthrough
  hosts: linuxserver
  become: yes

  vars:
    haproxy_cfg_path: /etc/haproxy/haproxy.cfg

  tasks:
    - name: Install HAProxy
      apt:
        name: haproxy
        state: present
        update_cache: yes

    - name: Configure HAProxy for HTTPS passthrough
      copy:
        dest: "{{ haproxy_cfg_path }}"
        content: |
          global
              log /dev/log    local0
              log /dev/log    local1 notice
              chroot /var/lib/haproxy
              stats socket /run/haproxy/admin.sock mode 660 level admin
              stats timeout 30s
              user haproxy
              group haproxy
              daemon

          defaults
              log     global
              mode    tcp
              option  tcplog
              timeout connect 5000
              timeout client  50000
              timeout server  50000

          frontend https_in
              bind *:443
              default_backend servers

          backend servers
              server backend1 192.168.1.103:443 check

    - name: Restart HAProxy
      service:
        name: haproxy
        state: restarted
        enabled: yes