---
- name: Install Prometheus monitoring on Ubuntu
  hosts: linuxserver
  become: yes

  vars:
    prometheus_version: "2.52.0"
    prometheus_user: prometheus
    prometheus_group: prometheus
    prometheus_install_dir: /opt/prometheus
    prometheus_data_dir: /var/lib/prometheus
    prometheus_config_dir: /etc/prometheus

  tasks:
    - name: Install required packages
      apt:
        name:
          - wget
          - tar
        state: present
        update_cache: yes

    - name: Create Prometheus user and group
      user:
        name: "{{ prometheus_user }}"
        shell: /usr/sbin/nologin
        system: yes
        create_home: no

    - name: Create directories
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
        mode: "0755"
      loop:
        - "{{ prometheus_install_dir }}"
        - "{{ prometheus_data_dir }}"
        - "{{ prometheus_config_dir }}"

    - name: Download Prometheus
      get_url:
        url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
        dest: "/tmp/prometheus.tar.gz"
        mode: "0644"

    - name: Extract Prometheus
      unarchive:
        src: "/tmp/prometheus.tar.gz"
        dest: "/tmp/"
        remote_src: yes

    - name: Copy Prometheus binaries
      copy:
        src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
        dest: "/usr/local/bin/{{ item }}"
        owner: root
        group: root
        mode: "0755"
      loop:
        - prometheus
        - promtool

    - name: Copy consoles and console_libraries
      copy:
        src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
        dest: "{{ prometheus_install_dir }}/{{ item }}"
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
        mode: "0755"
      loop:
        - consoles
        - console_libraries

    - name: Create Prometheus config file
      copy:
        dest: "{{ prometheus_config_dir }}/prometheus.yml"
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
        mode: "0644"
        content: |
          global:
            scrape_interval: 15s

          scrape_configs:
            - job_name: 'prometheus'
              static_configs:
                - targets: ['localhost:9090']

    - name: Create systemd service file for Prometheus
      copy:
        dest: /etc/systemd/system/prometheus.service
        mode: "0644"
        content: |
          [Unit]
          Description=Prometheus
          Wants=network-online.target
          After=network-online.target

          [Service]
          User={{ prometheus_user }}
          Group={{ prometheus_group }}
          Type=simple
          ExecStart=/usr/local/bin/prometheus \
            --config.file={{ prometheus_config_dir }}/prometheus.yml \
            --storage.tsdb.path={{ prometheus_data_dir }} \
            --web.console.templates={{ prometheus_install_dir }}/consoles \
            --web.console.libraries={{ prometheus_install_dir }}/console_libraries

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Enable and start Prometheus
      systemd:
        name: prometheus
        state: started
        enabled: yes